### ISSUE TITLE
How you binarize float vectors?

### ISSUE THREAD

**Issue by chasingegg** [tensorchord/pgvecto.rs-matryoshka-embeddings-benchmark#1]
It is very promising of binary vectors's performance and recall, I'm curious about how you binarize those float vectors, just a simle mapping like postive -> 1, negative -> 0 ? Could you point out the documentation if you have already mentioned it

**Comment by gaocegege** [comment]
Yes, here is the doc https://docs.pgvecto.rs/usage/vector-types.html#bvector-binary-vector

**Comment by chasingegg** [comment]
Thanks for the quick reply! So basically is like postive -> 1, negative/0->0 by `binarize` function, simple but effective

**Comment by gaocegege** [comment]
Yeah. It works well for OpenAI's embedding model.
